GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyNyIsImlkIjoiNjNhYTA1Y2QzZmI5MmZhZWQ3NjdhODU3IiwiaWF0IjoxNjcyMTI5NTgxLCJleHAiOjE2NzIxMzMxODF9.pkCxhnlHV_D0YkFYv0f90bFe-zEwKnYyOVHDw4W03qg 